[project]
name = "polygon_tally"
version = "0.1.0"
description = "Add a short description here"
authors = ["Joseph Specht <jspecht3@illinois.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
numpy = ">=2.0.1,<3"
pytest = ">=8.3.2,<9"
